version: '3'
 
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             gunicorn emenu.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=emenu
      - DB_USER=postgres
      - DB_PASS=$POSTGRES_PASS
    depends_on:
      - db
             
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=emenu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASS
    volumes: 
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
  
  celery:
    restart: always
    build:
      context: .
    command: celery -A emenu worker --loglevel=info -E -B
    environment:
      - DB_HOST=db
      - DB_NAME=emenu
      - DB_USER=postgres
      - DB_PASS=$POSTGRES_PASS
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - EMAIL_HOST=$EMAIL_HOST
    depends_on:
      - db
      - app
      - rabbitmq
volumes:
  pgdata: